"""RFC-011 bounded child-account acquisition reference slice."""

from __future__ import annotations

from itertools import count
from pathlib import Path
import uuid

import pytest

from foundry.core.acquisition import (
    AcquisitionError, AcquisitionProviderRegistry, AssetRegistration,
    AssetRegistry, CanonicalObservationProjection, ConfirmationGate,
    EnvelopeProjection, EvidenceUnavailable, EvidenceVault, ExternalRef,
    IdentityIndex, ManualAcquisitionProvider, ProposalInbox,
    ResolutionService, TelemetryStream, TelemetryStreamRegistry, ValuationLenses,
)
from foundry.eventlog import EventLog
from foundry.finance import entities as finance
from foundry.finance.acquisition import (
    FINANCE_MANUAL_DRAFT_CONTRACT,
    FinanceAccessibilityProjection,
    FinanceManualInterpreter,
)


HOUSEHOLD = "household-1"
CHILD = "child-1"
PARENT = "parent-1"
ACCOUNT = "account-1"
HOLDING = "holding-1"


@pytest.fixture
def deterministic_log(tmp_path, monkeypatch):
    """Every new RFC-011 builder receives deterministic substrate time/ids."""
    ticks = count(1_000.0, 1.0)
    ids = count(1)
    monkeypatch.setattr("foundry.eventlog.time.time", lambda: next(ticks))
    monkeypatch.setattr("foundry.eventlog.uuid.uuid4", lambda: uuid.UUID(int=next(ids)))
    return EventLog(tmp_path / "events.jsonl")


@pytest.fixture
def acquisition(deterministic_log, tmp_path):
    log = deterministic_log
    vault = EvidenceVault(tmp_path / "vault", authorized=lambda actor: actor == "reviewer")
    streams = TelemetryStreamRegistry(log)
    envelopes = EnvelopeProjection(log)
    inbox = ProposalInbox(log)
    identity = IdentityIndex(log)
    registry = AssetRegistry(log, entity_exists=lambda entity_id: entity_id in {ACCOUNT, HOLDING})
    resolver = ResolutionService(identity, registry, inbox)
    return log, vault, streams, envelopes, inbox, identity, registry, resolver


def _stream(identifier, subject, property):
    return TelemetryStream(
        id=identifier, subject_id=subject, property=property, channel="manual",
        refresh_policy="monthly", confirmation_policy="review_each",
        source_identity="user:reviewer", unit_or_currency="GBP",
        validation_contract="numeric observation", household_id=HOUSEHOLD,
        expected_cadence="monthly",
    )


def _provider(log, streams, vault, stream_ids):
    provider = ManualAcquisitionProvider(log, streams, vault, stream_ids)
    providers = AcquisitionProviderRegistry()
    providers.register(provider)
    return provider, providers


def _gate(log, inbox, streams, identity, registry):
    return ConfirmationGate(log, inbox, streams, identity, registry,
                            FINANCE_MANUAL_DRAFT_CONTRACT)


def _fact(kind, subject_id, valid_at, canonical_event, **extra):
    return {"kind": kind, "subject_id": subject_id, "valid_at": valid_at,
            "canonical_event": canonical_event, **extra}


def _capture_and_propose(provider, interpreter, envelope_projection, stream_id, fact,
                         received_at=100.0, external_ref=None):
    envelope = provider.capture(
        stream_id, {"observations": [fact]}, received_at=received_at,
        actor="reviewer", source_identity="user:reviewer", external_ref=external_ref)
    envelope_projection.rebuild()
    interpreter.envelopes.rebuild()
    return envelope, interpreter.interpret(envelope.id, "reviewer")


def _foundation(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    finance.declare_account(log, "jisa", "GBP", name="Child account", tax_wrapper="isa")
    # The deterministic id is generated by the substrate, but this helper uses
    # the supplied domain id in drafts so registry relationships stay explicit.
    log.append("finance.account.declared", {"entity_id": ACCOUNT, "account_type": "jisa",
               "currency": "GBP", "tax_wrapper": "isa", "name": "Child account"})
    finance.link_ownership(log, "account", ACCOUNT, "custodian", PARENT)
    finance.link_ownership(log, "account", ACCOUNT, "beneficial_owner", CHILD)
    registry.register(AssetRegistration(ACCOUNT, "finance", HOUSEHOLD))
    streams.declare(_stream("account-total", ACCOUNT, "statement_total"))
    streams.declare(_stream("holding-register", HOLDING, "holding_exists"))
    streams.declare(_stream("holding-units", HOLDING, "units"))
    streams.declare(_stream("holding-price", HOLDING, "price"))
    return FinanceManualInterpreter(vault, envelopes, streams, resolver), _gate(
        log, inbox, streams, identity, registry)


def test_manual_pipeline_captures_verbatim_evidence_then_confirms_canonical_state(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    interpreter, gate = _foundation(acquisition)
    provider, _ = _provider(log, streams, vault, {"holding-register", "holding-units", "holding-price"})

    holding = _fact("holding_exists", HOLDING, 10.0, {
        "kind": "finance.position.declared", "payload": {
            "entity_id": HOLDING, "account_id": ACCOUNT, "instrument": "Global tracker",
            "quantity": 0.0, "unit_price": 0.0, "currency": "GBP", "cost_basis": 0.0,
            "valuation_date": 10.0, "market_value": 0.0, "asset_category": "tracker_fund",
        }}, external_ref={"namespace": "isin", "value": "GB00TRACKER"},
        verbatim_note="this belongs in the evidence vault only")
    envelope, proposal = _capture_and_propose(provider, interpreter, envelopes, "holding-register", holding)
    assert not any(event["kind"].startswith("finance.position") for event in log.events())
    assert b"this belongs in the evidence vault only" not in Path(log.path).read_bytes()
    gate.confirm(proposal.id, actor="reviewer")
    registry = AssetRegistry(log, entity_exists=lambda entity_id: entity_id in {ACCOUNT, HOLDING})
    registry.register(AssetRegistration(HOLDING, "finance", HOUSEHOLD,
                                        (ExternalRef("isin", "GB00TRACKER"),)))
    registry.contain(ACCOUNT, HOLDING)
    inbox.rebuild()
    identity.rebuild()
    assert ResolutionService(identity, registry, inbox).resolve(
        HOUSEHOLD, ExternalRef("isin", "GB00TRACKER")).outcome == "resolved"
    assert vault.get(envelope.payload_hash, "reviewer")
    assert inbox.proposals[proposal.id].state == "confirmed"
    assert log.verify()


def test_units_price_and_container_total_are_distinct_streams_with_reconciliation(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    interpreter, gate = _foundation(acquisition)
    provider, _ = _provider(log, streams, vault, {"holding-register", "holding-units", "holding-price", "account-total"})
    register = _fact("holding_exists", HOLDING, 10.0, {"kind": "finance.position.declared", "payload": {
        "entity_id": HOLDING, "account_id": ACCOUNT, "instrument": "Global tracker", "quantity": 0.0,
        "unit_price": 0.0, "currency": "GBP", "cost_basis": 0.0, "valuation_date": 10.0,
        "market_value": 0.0, "asset_category": "tracker_fund"}},
        external_ref={"namespace": "isin", "value": "GB00TRACKER"})
    _, proposal = _capture_and_propose(provider, interpreter, envelopes, "holding-register", register)
    gate.confirm(proposal.id, actor="reviewer")
    registry = AssetRegistry(log, entity_exists=lambda entity_id: entity_id in {ACCOUNT, HOLDING})
    registry.register(AssetRegistration(HOLDING, "finance", HOUSEHOLD))
    registry.contain(ACCOUNT, HOLDING)
    identity.rebuild(); inbox.rebuild()
    interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams,
                                    ResolutionService(identity, registry, inbox))
    units = _fact("units", HOLDING, 20.0, {"kind": "finance.position.updated", "payload": {
        "entity_id": HOLDING, "quantity": 12.0}}, value=12.0, unit="units",
        external_ref={"namespace": "isin", "value": "GB00TRACKER"})
    _, unit_proposal = _capture_and_propose(provider, interpreter, EnvelopeProjection(log), "holding-units", units, 30.0, "statement-1")
    gate.confirm(unit_proposal.id, actor="reviewer")
    inbox.rebuild(); identity.rebuild()
    interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams,
                                    ResolutionService(identity, registry, inbox))
    price = _fact("price", HOLDING, 20.0, {"kind": "finance.position.updated", "payload": {
        "entity_id": HOLDING, "unit_price": 2.5, "valuation_date": 20.0}}, value=2.5, unit="GBP",
        external_ref={"namespace": "isin", "value": "GB00TRACKER"})
    _, price_proposal = _capture_and_propose(provider, interpreter, EnvelopeProjection(log), "holding-price", price, 31.0, "statement-2")
    gate.confirm(price_proposal.id, actor="reviewer")
    inbox.rebuild(); identity.rebuild()
    interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams,
                                    ResolutionService(identity, registry, inbox))
    total = _fact("statement_total", ACCOUNT, 20.0, {"kind": "finance.account.reconciliation_observed", "payload": {
        "entity_id": ACCOUNT, "supplied_total": 31.0}}, value=31.0, unit="GBP")
    _, total_proposal = _capture_and_propose(provider, interpreter, EnvelopeProjection(log), "account-total", total, 32.0, "statement-3")
    gate.confirm(total_proposal.id, actor="reviewer")
    lenses = ValuationLenses(registry, streams, CanonicalObservationProjection(log, EnvelopeProjection(log)))
    reconciliation = lenses.reconciliation(ACCOUNT, valid_at=20.0, known_at=9_999.0)
    assert reconciliation.derived_total == 30.0
    assert reconciliation.supplied_total == 31.0
    assert reconciliation.difference == -1.0
    assert reconciliation.confidence == "Provisional"


def test_capture_is_idempotent_and_provider_registry_fails_closed(acquisition):
    log, vault, streams, envelopes, *_ = acquisition
    streams.declare(_stream("units", HOLDING, "units"))
    provider, providers = _provider(log, streams, vault, {"units"})
    payload = {"observations": [_fact("units", HOLDING, 10.0, {"kind": "finance.position.updated", "payload": {
        "entity_id": HOLDING, "quantity": 1.0}}, value=1.0)]}
    first = provider.capture("units", payload, received_at=20, actor="reviewer", source_identity="user:reviewer", external_ref="same")
    second = provider.capture("units", payload, received_at=20, actor="reviewer", source_identity="user:reviewer", external_ref="same")
    assert first == second
    assert sum(event["kind"] == "core.telemetry_envelope.declared" for event in log.events()) == 1
    with pytest.raises(AcquisitionError):
        providers.provider_for("unknown")
    with pytest.raises(AcquisitionError):
        providers.register(provider)


def test_unresolved_update_ambiguous_identity_and_rejection_fail_closed(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    streams.declare(_stream("units", HOLDING, "units"))
    provider, _ = _provider(log, streams, vault, {"units"})
    interpreter = FinanceManualInterpreter(vault, envelopes, streams, resolver)
    gate = _gate(log, inbox, streams, identity, registry)
    fact = _fact("units", HOLDING, 10, {"kind": "finance.position.updated", "payload": {
        "entity_id": HOLDING, "quantity": 1}}, value=1, external_ref={"namespace": "isin", "value": "UNKNOWN"})
    _, proposal = _capture_and_propose(provider, interpreter, envelopes, "units", fact)
    with pytest.raises(AcquisitionError, match="unresolved"):
        gate.confirm(proposal.id, actor="reviewer")
    gate.reject(proposal.id, actor="reviewer", reason="identity needs review")
    assert not any(event["kind"].startswith("finance.") for event in log.events())
    identity.declare(HOUSEHOLD, ExternalRef("isin", "DUP"), HOLDING, "prior", "reviewer")
    identity.declare(HOUSEHOLD, ExternalRef("isin", "DUP"), "holding-2", "prior", "reviewer")
    identity.rebuild()
    assert ResolutionService(identity, registry).resolve(HOUSEHOLD, ExternalRef("isin", "DUP")).outcome == "ambiguous"


def test_vault_authorization_hash_integrity_redaction_and_hostile_input(acquisition):
    log, vault, streams, *_ = acquisition
    streams.declare(_stream("units", HOLDING, "units"))
    provider, _ = _provider(log, streams, vault, {"units"})
    with pytest.raises(EvidenceUnavailable):
        vault.put(b"x", "intruder")
    with pytest.raises(AcquisitionError, match="secrets"):
        provider.capture("units", {"observations": [{"password": "no"}]}, received_at=1,
                         actor="reviewer", source_identity="user:reviewer")
    envelope = provider.capture("units", {"observations": [_fact("units", HOLDING, 1, {
        "kind": "finance.position.updated", "payload": {"entity_id": HOLDING, "quantity": 1}}, value=1)]},
        received_at=2, actor="reviewer", source_identity="user:reviewer")
    path = vault.root / envelope.payload_hash
    path.write_bytes(b"tampered")
    with pytest.raises(EvidenceUnavailable, match="hash mismatch"):
        vault.get(envelope.payload_hash, "reviewer")
    path.write_bytes(b"restored")
    # A redaction event is still append-only; missing evidence is explicit.
    payload_hash, _ = vault.put(b"redactable", "reviewer")
    vault.redact(log, payload_hash, "requested", "reviewer")
    with pytest.raises(EvidenceUnavailable, match="missing or redacted"):
        vault.get(payload_hash, "reviewer")


def test_registry_rejects_unknown_duplicate_cross_household_and_cycles(acquisition):
    log, _, _, _, _, _, _, _ = acquisition
    registry = AssetRegistry(log, entity_exists=lambda value: value in {"a", "b", "c"})
    with pytest.raises(AcquisitionError, match="unknown"):
        registry.register(AssetRegistration("missing", "finance", HOUSEHOLD))
    registry.register(AssetRegistration("a", "finance", HOUSEHOLD))
    registry.register(AssetRegistration("b", "finance", HOUSEHOLD))
    registry.register(AssetRegistration("c", "finance", "other-household"))
    with pytest.raises(AcquisitionError, match="duplicate"):
        registry.register(AssetRegistration("a", "finance", HOUSEHOLD))
    registry.contain("a", "b")
    with pytest.raises(AcquisitionError):
        registry.contain("b", "a")
    with pytest.raises(AcquisitionError, match="cross-household"):
        registry.contain("a", "c")


def test_bitemporal_reads_preserve_late_arrival_and_substrate_recorded_at(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    streams.declare(_stream("units", HOLDING, "units"))
    provider, _ = _provider(log, streams, vault, {"units"})
    interpreter = FinanceManualInterpreter(vault, envelopes, streams, resolver)
    gate = _gate(log, inbox, streams, identity, registry)
    # A new holding declaration makes the unresolved ISIN a reviewable new subject.
    register = _fact("holding_exists", HOLDING, 1, {"kind": "finance.position.declared", "payload": {
        "entity_id": HOLDING, "account_id": ACCOUNT, "instrument": "Tracker", "quantity": 0,
        "unit_price": 0, "currency": "GBP", "cost_basis": 0, "valuation_date": 1,
        "market_value": 0, "asset_category": "tracker_fund"}}, external_ref={"namespace": "isin", "value": "TIME"})
    # The register stream is separately declared to keep stream semantics explicit.
    streams.declare(_stream("register", HOLDING, "holding_exists"))
    provider = ManualAcquisitionProvider(log, streams, vault, {"register", "units"})
    _, registration = _capture_and_propose(provider, interpreter, envelopes, "register", register, 50, "document-0")
    gate.confirm(registration.id, actor="reviewer")
    inbox.rebuild(); identity.rebuild()
    interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams, ResolutionService(identity, registry, inbox))
    first = _fact("units", HOLDING, 10, {"kind": "finance.position.updated", "payload": {
        "entity_id": HOLDING, "quantity": 2}}, value=2, external_ref={"namespace": "isin", "value": "TIME"})
    _, proposal = _capture_and_propose(provider, interpreter, EnvelopeProjection(log), "units", first, 100, "document-1")
    events = gate.confirm(proposal.id, actor="reviewer")
    assert "recorded_at" not in events[0]["payload"]
    recorded = events[0]["ts"]
    projection = CanonicalObservationProjection(log, EnvelopeProjection(log))
    known_then = projection.latest(HOLDING, "units", valid_at=10, known_at=recorded)
    assert known_then and known_then.valid_at == 10 and known_then.received_at == 100
    assert known_then.recorded_at == recorded
    assert log.verify()


def test_accessibility_lifecycle_and_mission_lenses_are_derived_not_stored(acquisition):
    log, vault, streams, envelopes, inbox, identity, registry, resolver = acquisition
    interpreter, gate = _foundation(acquisition)
    provider, _ = _provider(log, streams, vault, {"holding-register", "holding-units", "holding-price"})
    register = _fact("holding_exists", HOLDING, 1, {"kind": "finance.position.declared", "payload": {
        "entity_id": HOLDING, "account_id": ACCOUNT, "instrument": "Tracker", "quantity": 0,
        "unit_price": 0, "currency": "GBP", "cost_basis": 0, "valuation_date": 1,
        "market_value": 0, "asset_category": "tracker_fund"}}, external_ref={"namespace": "isin", "value": "ACCESS"})
    _, proposal = _capture_and_propose(provider, interpreter, envelopes, "holding-register", register)
    gate.confirm(proposal.id, actor="reviewer")
    registry = AssetRegistry(log, entity_exists=lambda entity_id: entity_id in {ACCOUNT, HOLDING})
    registry.register(AssetRegistration(HOLDING, "finance", HOUSEHOLD)); registry.contain(ACCOUNT, HOLDING)
    inbox.rebuild(); identity.rebuild()
    interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams, ResolutionService(identity, registry, inbox))
    for stream_id, kind, value, payload in (
        ("holding-units", "units", 10.0, {"entity_id": HOLDING, "quantity": 10.0}),
        ("holding-price", "price", 4.0, {"entity_id": HOLDING, "unit_price": 4.0, "valuation_date": 5.0}),
    ):
        fact = _fact(kind, HOLDING, 5, {"kind": "finance.position.updated", "payload": payload}, value=value,
                     external_ref={"namespace": "isin", "value": "ACCESS"})
        _, proposal = _capture_and_propose(provider, interpreter, EnvelopeProjection(log), stream_id, fact, 6, stream_id)
        gate.confirm(proposal.id, actor="reviewer")
        inbox.rebuild(); identity.rebuild()
        interpreter = FinanceManualInterpreter(vault, EnvelopeProjection(log), streams, ResolutionService(identity, registry, inbox))
    # Profiles and condition transitions are Finance assertions, read through
    # Core's domain-neutral lifecycle projection; no statutory rule enters Core.
    log.append("finance.accessibility_profile.declared", {"entity_id": HOLDING, "components": [
        {"portion": 1.0, "condition": "age_gate", "condition_ref": "gate-1", "earliest_at": 100.0}],
        "provenance": {"proposal_id": "p", "evidence_id": "e", "confirmed_by": "reviewer"}})
    log.append("finance.accessibility_condition.declared", {"entity_id": "gate-1", "subject_id": HOLDING,
        "condition": "age_gate", "state": "pending", "provenance": {"proposal_id": "p"}})
    access = FinanceAccessibilityProjection(log)
    lenses = ValuationLenses(registry, streams, CanonicalObservationProjection(log, EnvelopeProjection(log)))
    restricted = lenses.accessibility_value(HOLDING, valid_at=5, known_at=9_999,
                                            profile=access.profile_for(HOLDING), conditions=access.condition_states())
    future = lenses.accessibility_value(HOLDING, valid_at=5, known_at=9_999,
                                        profile=access.profile_for(HOLDING), conditions=access.condition_states(), horizon=100)
    assert restricted["value"] == 0.0
    assert future["value"] == 40.0
    assert lenses.mission_value(HOLDING, valid_at=5, known_at=9_999, profile=access.profile_for(HOLDING),
                                conditions=access.condition_states(), horizon=None,
                                policy=lambda value, quality: 0.0)["value"] == 0.0
    assert lenses.mission_value(HOLDING, valid_at=5, known_at=9_999, profile=access.profile_for(HOLDING),
                                conditions=access.condition_states(), horizon=100,
                                policy=lambda value, quality: value)["value"] == 40.0
    log.append("finance.accessibility_condition.updated", {"entity_id": "gate-1", "state": "satisfied",
        "provenance": {"proposal_id": "p", "evidence_id": "e", "confirmed_by": "reviewer"}})
    log.append("finance.accessibility_condition.updated", {"entity_id": "gate-1", "state": "revoked",
        "provenance": {"proposal_id": "p", "evidence_id": "e", "confirmed_by": "reviewer"}})
    access = FinanceAccessibilityProjection(log)
    assert access.conditions["gate-1"].state == "satisfied"  # terminal states never rewind


def test_missing_material_market_evidence_remains_unknown_not_zero(acquisition):
    log, _, streams, _, _, _, registry, _ = acquisition
    registry.register(AssetRegistration(HOLDING, "finance", HOUSEHOLD))
    streams.declare(_stream("holding-units", HOLDING, "units"))
    log.append("finance.position.updated", {
        "entity_id": HOLDING,
        "provenance": {"evidence_id": "evidence-1", "proposal_id": "proposal-1", "confirmed_by": "reviewer"},
        "observation": {"subject_id": HOLDING, "stream_id": "holding-units", "kind": "units",
                        "value": 12.0, "valid_at": 10.0, "observed_at": 10.0,
                        "evidence_grade": "declared"},
    })
    lenses = ValuationLenses(registry, streams, CanonicalObservationProjection(log, EnvelopeProjection(log)))
    market = lenses.market_value(HOLDING, valid_at=10.0, known_at=9_999.0)
    accessible = lenses.accessibility_value(HOLDING, valid_at=10.0, known_at=9_999.0,
                                            profile={"components": [{"condition": "none", "portion": 1.0}]},
                                            conditions={})
    mission = lenses.mission_value(HOLDING, valid_at=10.0, known_at=9_999.0,
                                   profile={"components": [{"condition": "none", "portion": 1.0}]},
                                   conditions={}, horizon=None, policy=lambda value, quality: value)
    reconciliation = lenses.reconciliation(HOLDING, valid_at=10.0, known_at=9_999.0)
    assert market["value"] is None and market["confidence"] == "Insufficient"
    assert accessible["value"] is None and mission["value"] is None
    assert reconciliation.derived_total is None and reconciliation.difference is None
    assert reconciliation.confidence == "Insufficient"
    assert lenses.market_value(HOLDING, valid_at=10.0, known_at=9_999.0) == market


def test_identity_and_duplicate_protection_refuse_operation_when_inbox_is_unavailable(acquisition):
    log, vault, streams, envelopes, _, identity, registry, _ = acquisition
    streams.declare(_stream("units", HOLDING, "units"))
    provider, _ = _provider(log, streams, vault, {"units"})
    resolver = ResolutionService(identity, registry)
    with pytest.raises(AcquisitionError, match="duplicate protection"):
        resolver.semantic_duplicate("units", HOLDING, "units", 10.0, "statement")
    envelope = provider.capture("units", {"observations": [_fact("units", HOLDING, 10.0, {
        "kind": "finance.position.updated", "payload": {"entity_id": HOLDING, "quantity": 1.0}}, value=1.0)]},
        received_at=20.0, actor="reviewer", source_identity="user:reviewer")
    envelopes.rebuild()
    with pytest.raises(AcquisitionError, match="duplicate protection"):
        FinanceManualInterpreter(vault, envelopes, streams, resolver).interpret(envelope.id, "reviewer")


def test_core_acquisition_contract_contains_no_finance_event_vocabulary():
    source = Path(__file__).parents[1] / "src" / "foundry" / "core" / "acquisition.py"
    assert "finance." not in source.read_text()
